version: '3'
services:
  postgres: 
    image: 'postgres:latest'
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - 3050:80
  api: 
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - MONGODBADDR=mongo
      - MONGOUSER=root
      - MONGOPASS=example
      - JWTSECRET=kjhsdswertfdgcxfvbdtgxsdrgs
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - ./client:/app
      - /app/node_modules
  worker: 
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    ports: 
      - '9001:9001'
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
